[toolchain]
package_manager = "yarn"
channel = "1.79.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
market_factory = "CCLkxLFFCiBW57nphnjr2QMEMTahwL77JQNRq57VB932"
settlement = "BzoHHkUdTgkEqwQj5uDqkwKfgSW65QCL4GzGCafBJCz8"

[programs.devnet]
market_factory = "CCLkxLFFCiBW57nphnjr2QMEMTahwL77JQNRq57VB932"
settlement = "BzoHHkUdTgkEqwQj5uDqkwKfgSW65QCL4GzGCafBJCz8"

[programs.mainnet]
market_factory = "CCLkxLFFCiBW57nphnjr2QMEMTahwL77JQNRq57VB932"
settlement = "BzoHHkUdTgkEqwQj5uDqkwKfgSW65QCL4GzGCafBJCz8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.bankrun.ts"

[test]
startup_wait = 60000
