[toolchain]
package_manager = "yarn"
channel = "1.79.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
market_factory = "AQR7DVzsy1dKM3TdRqLMbzAb5waubBJYdXd9BGuCtVpR"
settlement = "8oErexD9Jgq6CfZvqGToAorLk1EHcdvKnNpcmfTen1XU"

[programs.devnet]
market_factory = "AQR7DVzsy1dKM3TdRqLMbzAb5waubBJYdXd9BGuCtVpR"
settlement = "8oErexD9Jgq6CfZvqGToAorLk1EHcdvKnNpcmfTen1XU"

[programs.mainnet]
market_factory = "AQR7DVzsy1dKM3TdRqLMbzAb5waubBJYdXd9BGuCtVpR"
settlement = "8oErexD9Jgq6CfZvqGToAorLk1EHcdvKnNpcmfTen1XU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 60000
