name = "karmapi-prediction-markets"
main = ".open-next/worker.js"
compatibility_date = "2025-05-05"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
NEXT_PUBLIC_SOLANA_RPC_URL = "https://api.devnet.solana.com"
NEXT_PUBLIC_PROGRAM_ID = "CCLkxLFFCiBW57nphnjr2QMEMTahwL77JQNRq57VB932"
NEXT_PUBLIC_BET_TOKEN_MINT = "So11111111111111111111111111111111111111112"
